main: cc.carm.outsource.plugin.coreprotectaddon.Main
name: ${project.name}

version: ${project.version}
description: ${project.description}
website: ${project.url}

authors:
  - CarmJos
  - Loliiiico

api-version: 1.16

softdepend:
  - CoreProtect

permissions:
  coreprotectaddon.command.query:
    description: 允许使用查询命令。
    default: op

commands:
  coreprotectquery:
    description: COQ 独立 lookup 查询（/coq help）。
    usage: /coq help
    aliases: [ coq ]
